services:
  streamdl:
    build: .
    container_name: streamdl
    ports:
      - "8082:8080"
    env_file:
      - .env
    volumes:
      - ./temp_downloads:/app/temp_downloads
    restart: unless-stopped


